; ============================================================
; ESP32-S3 DevKitC-1 (target for OV3660 adaptation)
; ============================================================

[env:esp32s3]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

; --- Upload ---
upload_protocol = esptool
upload_speed    = 921600
upload_port     = COM17

; --- Serial monitor ---
monitor_speed   = 115200
monitor_port    = COM19
monitor_filters = esp32_exception_decoder, colorize

; --- Build ---
board_build.flash_size = 16MB
board_build.psram = enabled
board_build.arduino.memory_type = qio_opi

build_flags =
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DCORE_DEBUG_LEVEL=3
  -DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192

; partition scheme with 3 MB app (camera needs space)
board_build.partitions = huge_app.csv

lib_deps =

